### ISSUE TITLE
possible bug in data_utils.py

### ISSUE THREAD

**Issue by yuvalkirstain** [abrazinskas/Copycat-abstractive-opinion-summarizer#2]
some reviews don't have all the necessary keys (such as reviewText). It causes the program to crash. I added the following lines:
```
if any((du_key not in du for du_key in amazon_to_output_map.keys())):
            continue
```
to line 72 , in the read_amazon_data function in data_utils.py module.
It seems to solve it. 

On another note, your repo is wonderful! It was so easy and nice to run!! Thank you !!

**Comment by chosenone75** [comment]
Hi, have you run the repo successfully? Are the summaries the model generates fluent?

**Comment by abrazinskas** [comment]
Thank you! Added your line to the script.
